name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: pip install -r API/requirements.txt  

    - name: Run unit test
      run: |
        cd API/unit_test
        python3 -m unittest test_api.py
